#!/usr/bin/zsh

# Configure powerlevel10k zsh theme
ln .zshrc .p10k.zsh $HOME/
git clone --depth=1 https://github.com/romkatv/powerlevel10k.git ${ZSH_CUSTOM:-$HOME/.oh-my-zsh/custom}/themes/powerlevel10k
